version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: prospects_watcher
      POSTGRES_PASSWORD: password
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - '5433:5432'
  web: &app_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/prospects_watcher
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpacker:
    build: .
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: "bin/webpack-dev-server"
    ports:
      - "3035:3035"
    depends_on:
      - web
    tty: false
    stdin_open: false

volumes:
  db-data:
