version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: prospects_watcher
      POSTGRES_PASSWORD: password
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - '5433:5432'
  webpacker:
    build: .
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

    command: "bin/webpack-dev-server"
    ports:
      - "3035:3035"
    tty: false
    stdin_open: false

volumes:
  db-data:
