version: '3'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: prospects_watcher
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prospects_watcher_development
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - '5433:5432'

volumes:
  db-data:
